# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c4859d0c3f064cf2034e51384f9bc97f521cb06c6f1e47832b0e4053865ee8be94d547701e4a68f0e94ef244b988933a8fe814aeb81e04d87b4fd7d59f0df2c

test:
  secret_key_base: 63a68dd53437482bb79fc2442b2125a898bd6cd05f0d9ba81f402a07ce141ef6a506e7f18535dca601618dd625bd0927de7d888f89182d9336034799ea7cea5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
